# Site settings
title: Xiaomeng Ma
email: xm2158@tc.columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  Xiaomeng Ma's website
baseurl: /home/
url:  xiaomeng-ma.github.io
twitter_username: twitter_username
github_username:  github_username
social:
  name: Xiaomeng Ma
  links: https://www.linkedin.com/in/amyxiaomengma/
  
# Build settings
markdown: kramdown
google_analytics: UA-152691063-1
highlighter: rouge
plugins: 
  - jekyll-seo-tag
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  research:
    output: true
    permalink: /research/:path/


